# Generated by Django 2.1.4 on 2019-02-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('intervalo', models.IntegerField(blank=True, default=4500, null=True, verbose_name='Digite o intervalo em que o banner irá deslizar em milisegundos')),
                ('ocultartitulo', models.BooleanField(default=False, verbose_name='Marque para ocultar o título do banner')),
                ('chave_estrangeira_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Jogo')),
            ],
        ),
        migrations.CreateModel(
            name='FotoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Nome')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='photo/banner', verbose_name='Imagem do banner')),
                ('url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Digite uma URL para a imagem')),
                ('posicao', models.IntegerField(blank=True, default=0, null=True)),
                ('mostrartitulobanner', models.BooleanField(default=False, verbose_name='Marque para ocultar o título do banner')),
                ('bannery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banner.Banner', verbose_name='Banner JOGOl')),
            ],
        ),
    ]
