# Generated by Django 2.1.4 on 2019-01-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, verbose_name='Nome da url')),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='JogoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, verbose_name='Nome da url')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.CategoriaModel')),
            ],
            options={
                'verbose_name': 'Jogo',
                'ordering': ['nome'],
            },
        ),
    ]
